INSERT INTO sensor ( sensor_coordinates, sensor_status )
VALUES
	(point(0,0), true),
	(point(1,0), true),
	(point(2,0), true),
	(point(3,0), true),
	(point(4,0), true),
	(point(5,0), true),
	(point(6,0), true),
	(point(7,0), true),
	(point(8,0), true),
	(point(9,0), true),
	
	(point(0,1), true),
	(point(1,1), true),
	(point(2,1), true),
	(point(3,1), true),
	(point(4,1), true),
	(point(5,1), true),
	(point(6,1), true),
	(point(7,1), true),
	(point(8,1), true),
	(point(9,1), true),
	
	(point(0,2), true),
	(point(1,2), true),
	(point(2,2), true),
	(point(3,2), true),
	(point(4,2), true),
	(point(5,2), true),
	(point(6,2), true),
	(point(7,2), true),
	(point(8,2), true),
	(point(9,2), true),
	
	(point(0,3), true),
	(point(1,3), true),
	(point(2,3), true),
	(point(3,3), true),
	(point(4,3), true),
	(point(5,3), true),
	(point(6,3), true),
	(point(7,3), true),
	(point(8,3), true),
	(point(9,3), true),
	
	(point(0,4), true),
	(point(1,4), true),
	(point(2,4), true),
	(point(3,4), true),
	(point(4,4), true),
	(point(5,4), true),
	(point(6,4), true),
	(point(7,4), true),
	(point(8,4), true),
	(point(9,4), true),
	
	(point(0,5), true),
	(point(1,5), true),
	(point(2,5), true),
	(point(3,5), true),
	(point(4,5), true),
	(point(5,5), true),
	(point(6,5), true),
	(point(7,5), true),
	(point(8,5), true),
	(point(9,5), true);